name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [ 14, 16, 18 ]

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node Version
        uses: actions/setup-node@v4
        with:
          node-version: 20 
          cache: 'yarn'

      - run: yarn
      - run: yarn run test

      - name: Build docker image
        run: docker build -t jv-api:latest .