name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node Version > ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:                          # Corrigido o alinhamento do "with"
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - run: yarn
      - run: yarn run test